name: calley_automatic_dialer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  go_router: ^14.8.0
  flutter_svg: ^2.0.17
  dio: ^5.4.0
  equatable: ^2.0.5
  http: ^1.3.0
  pin_code_fields: ^8.0.0
  url_launcher: ^6.2.5
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.0.0-beta.22


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
